### ISSUE TITLE
fs exception on game start

### ISSUE THREAD

**Issue by unresolvedsymbol** [Codec-J/PokemonXYCTRPFLite#1]
A boot.firm included in a closed source plugin release seems very strange, the exception occurs on the latest release of Luma3DS-3GX

**Comment by Codec-J** [comment]
Say what you want to say. The boot.firm is from Nanquitas' Discord server, you may head over there and download it instead if you'd like. I only included the boot.firm due to people complaining how hard it is to find the correct one. "the exception occurs on the latest release of Luma3DS-3GX," if you're using the boot.firm I gave then it should work fine. For more help, contact me on Discord
